services:
  banco:
    image: mysql:8.0
    container_name: uniqprint-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: uniqprint_db
      MYSQL_USER: uniqprint_user
      MYSQL_PASSWORD: uniqprint_password
    ports:
      - "3307:3306"
    volumes:
      - uniqprint_mysql_data:/var/lib/mysql

volumes:
  uniqprint_mysql_data:
